sudo: require

language: cpp

os:
    - linux

compiler:
    - gcc
    - clang

dist: trusty

before_install:
    - echo BEFORE_INSTALLATION
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-5
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
    - sudo apt-get -qq update
    - sudo apt-get install -y libgtest-dev valgrind cmake
    - sudo wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
    - sudo tar xf release-1.8.0.tar.gz
    - cd googletest-release-1.8.0
    - sudo cmake -DBUILD_SHARED_LIBS=ON .
    - sudo make
    - ls
    - sudo cp -a include/gtest /usr/include
    - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
    - which valgrind
    - cd "${TRAVIS_BUILD_DIR}"
    - echo AFTER_INSTALLATION

script:
    - cmake CMakeLists.txt
    - make
    - ./RefactoringKata
