sudo: require

language: cpp

os:
    - linux

compiler:
    - gcc
    - clang

dist: trusty

source:
    - CI/gcc_install.sh
    - CI/cmake_install.sh
    - CI/gtest_install.sh

matrix:
    - os: osx 

script:
    - cmake CMakeLists.txt
    - make
    - ./RefactoringKata
